apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: {{ .Values.namespace | default "default" }}{{ required "An env-suffix is needed" .Values.env-suffix }}
  labels:
    app: helm-nginx-{{ required "An env-suffix is needed" .Values.env-suffix }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: helm-nginx-{{ required "An env-suffix is needed" .Values.env-suffix }}
  template:
    metadata:
      namespace: {{ .Values.namespace | default "default" }}{{ required "An env-suffix is needed" .Values.env-suffix }}
      labels:
        app: helm-nginx-{{ required "An env-suffix is needed" .Values.env-suffix }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/usr/share/nginx/html"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: helm-nginx-config
