apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: helm-nginx
  labels:
    app: helm-nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: helm-nginx
  template:
    metadata:
      namespace: helm-nginx
      labels:
        app: helm-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
          protocol: TCP
        volumeMounts:
        - name: config
          mountPath: "/usr/share/nginx/html"
          readOnly: true
      volumes:
        - name: config
          configMap:
            name: helm-nginx-config
