apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: helm-nginx-ingress
  namespace: {{ .Values.namespace | default "default" }}{{ required "An env-suffix is needed" .Values.env-suffix }}
spec:
  rules:
  - http:
      paths:
      - path: /*
        pathType: ImplementationSpecific
        backend:
          service:
            name: helm-nginx-service
            port:
              number: 80
