apiVersion: v1
kind: Service
metadata:
  name: helm-nginx-service
  namespace: helm-nginx  
  labels:
    app: helm-nginx
spec:
  type: ClusterIP
  selector:
    app: helm-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
