apiVersion: v1
kind: Service
metadata:
  name: helm-nginx-service
  namespace: {{ .Values.namespace | default "default" }}{{ required "An env-suffix is needed" .Values.env-suffix }}  
  labels:
    app: helm-nginx
spec:
  type: ClusterIP
  selector:
    app: helm-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
